### ISSUE TITLE
Robustness for delta editor

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/kaleidoscope-ui#5]
```
java.lang.NullPointerException
	at com.kaleidoscope.ui.delta.visualisation.DeltaDiagramTextProvider.supportsEditor(DeltaDiagramTextProvider.java:72)
	at net.sourceforge.plantuml.eclipse.views.AbstractDiagramSourceView.updateDiagramText(AbstractDiagramSourceView.java:279)
	at net.sourceforge.plantuml.eclipse.views.AbstractDiagramSourceView.updateDiagramText(AbstractDiagramSourceView.java:262)
	at net.sourceforge.plantuml.eclipse.views.AbstractDiagramSourceView$1.updateDiagramText(AbstractDiagramSourceView.java:209)
	at net.sourceforge.plantuml.eclipse.views.AbstractDiagramSourceView$1.partActivated(AbstractDiagramSourceView.java:205)
	at org.eclipse.ui.internal.WorkbenchPage$14.run(WorkbenchPage.java:4990)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.WorkbenchPage.firePartActivated(WorkbenchPage.java:4987)
	at org.eclipse.ui.internal.WorkbenchPage.access$19(WorkbenchPage.java:4975)
	at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:212)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:250)

```

**Comment by anthonyanjorin** [comment]
This flies when some files (jpeg) are opened.
